"""Initial migration

Revision ID: 938cb525eabf
Revises: 
Create Date: 2024-11-18 12:53:22.740157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '938cb525eabf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('identifier_code', table_name='motorcycles')
    op.drop_index('license_plate', table_name='motorcycles')
    op.drop_table('motorcycles')
    op.drop_index('identifier', table_name='plans')
    op.drop_table('plans')
    op.drop_index('identifier', table_name='rentals')
    op.drop_table('rentals')
    op.drop_index('identifier_code', table_name='deliverypersons')
    op.drop_index('license_number', table_name='deliverypersons')
    op.drop_index('tax_id', table_name='deliverypersons')
    op.drop_table('deliverypersons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverypersons',
    sa.Column('identifier_code', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('tax_id', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=14), nullable=False),
    sa.Column('license_number', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=11), nullable=False),
    sa.Column('license_category', mysql.CHAR(collation='utf8mb3_unicode_ci', length=2), nullable=False),
    sa.Column('license_image', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('identifier_code'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('tax_id', 'deliverypersons', ['tax_id'], unique=True)
    op.create_index('license_number', 'deliverypersons', ['license_number'], unique=True)
    op.create_index('identifier_code', 'deliverypersons', ['identifier_code'], unique=True)
    op.create_table('rentals',
    sa.Column('identifier', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('expected_end_date', sa.DATE(), nullable=True),
    sa.Column('additional_fee', mysql.FLOAT(), nullable=True),
    sa.Column('penalty_percentage', mysql.FLOAT(), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('identifier'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('identifier', 'rentals', ['identifier'], unique=True)
    op.create_table('plans',
    sa.Column('identifier', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('decription', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50), nullable=False),
    sa.Column('daily_rate', mysql.FLOAT(), nullable=False),
    sa.Column('days_quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('identifier', 'plans', ['identifier'], unique=True)
    op.create_table('motorcycles',
    sa.Column('identifier_code', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('license_plate', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=10), nullable=False),
    sa.Column('model', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50), nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('identifier_code'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('license_plate', 'motorcycles', ['license_plate'], unique=True)
    op.create_index('identifier_code', 'motorcycles', ['identifier_code'], unique=True)
    # ### end Alembic commands ###
